### ISSUE TITLE
깃허브 소셜로그인

### ISSUE THREAD

**Issue by somsom13** [Capstone-SSU/backend#10]
### 기능
---
깃허브로 회원가입 시,
1. 닉네임 중복 체크
2-1. 중복인 경우; 닉네임 폼으로 전환
2-2. 중복이 아닌 경우: 로그인 성공 후 화면으로 전환
3. 닉네임 입력 성공 후 로그인 후 디폴트 화면으로 전환
### Task
---
- [x] company 필드 자동 등록 기능 삭제
- [x] 로그인 시 정보 자동 업데이트 기능 삭제 
- [x] github  url용 username 별도 저장  기능 추가
- [x] 닉네임 중복체크용 api 구현
- [x] 소셜로그인 JWT로 변경 -> 세션-쿠키 인증방식 CORS라서 안됨^^^^^^^^^^ 아오아오아오아오 
- [ ] 깃허브 소셜로그인 JWT React 연동 테스트
